scenario:
  simpl: # only relevant for PyPSA-Eur
    - ''
  clusters: # number of nodes in Europe, any integer between 37 (1 node per country-zone) and several hundred
    - 45
  planning_horizons: # investment years for myopic and perfect; for overnight, year of cost assumptions can be different and is defined under 'costs'
    - 2020
    #- 2025
    #- 2030
    #- 2035
    #- 2040
    #- 2045 
    #- 2050

# CO2 budget as a fraction of 1990 emissions
# this is over-ridden if CO2Lx is set in sector_opts
# this is also over-ridden if cb is set in sector_opts
co2_budget:
  2020: 0.7011648746
  2025: 0.5241935484
  2030: 0.2970430108
  2035: 0.1500896057
  2040: 0.0712365591
  2045: 0.0322580645
  2050: 0
  
sector:  
  bev_charge_efficiency: 0.9  #BEV (dis-)charging efficiency
  bev_bat_to_wheel_efficiency: 0.91
  transport_internal_combustion_efficiency: 0.3    
  bev_dsm: true #turns on EV battery
  v2g: false #true #allows feed-in to grid from EV battery
  bev_energy: 0.05  #average battery size in MWh
  EV_charge_rate: 0.011 #MWh/h
  EV_consumption_1car: 0.01 #MWh_elec/hour (assuming 0.2 kWh/km https://github.com/PyPSA/pypsa-eur/blob/1fbe971ab8dab60d972d3a7b905b9cec7171c0ad/config/config.default.yaml#L382 and velocity of 50km/h
  ICE_consumption_1car: 0.033 #MWh_oil/hour (assuming 0.66 kWh_oil/km and 50 km/h (with the link efficiency 0.3, they are equivalent to 0.01 MWh_elec/hour)
  H2_consumption_1car: 0.02 #MWh_H2/hour (assuming KWh_H2/km and 50km/h) (with efficiency 0.5, they are equivalent to 0.01 MWh_elec/hour)
  H2_car_efficiency: 0.48
  energy_to_cars: 0.01 #Mw@wheel/car assuming 0.2kwh/km and 50km/h


costs:
  year: 2030
  version: v0.5.0
  rooftop_share: 0.14  # based on the potentials, assuming  (0.1 kW/m2 and 10 m2/person)
  fill_values:
    FOM: 0
    VOM: 0
    efficiency: 1
    fuel: 0
    investment: 0
    lifetime: 25
    "CO2 intensity": 0
    "discount rate": 0.07
  # Marginal and capital costs can be overwritten
  # capital_cost:
  #   onwind: 500
  marginal_cost:
    solar: 0.01
    onwind: 0.015
    offwind: 0.015
    hydro: 0.
    H2: 100.
    electrolysis: 0.
    fuel cell: 0.
    battery: 0.
    battery inverter: 0.

  capital_cost: # per car cost 
    H2_vehicle:  33_200 # €/cars
    ICE_vehicle: 25_000 # €/car
    E_vehicle:  25_600 # 24600€/car + 1000 €/charger
  emission_prices: # in currency per tonne emission, only used with the option Ep
  co2: 0.  
